# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170226_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='vouchers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='description',
            field=models.TextField(),
        ),
    ]
