# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170305_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=11)),
                ('last', models.DecimalField(decimal_places=2, max_digits=11)),
                ('name', models.CharField(max_length=200)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('quota', models.PositiveIntegerField()),
                ('qtyTracked', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='trackee',
            name='trackerCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tracker'),
        ),
    ]
