# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171221_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackee',
            name='last',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trackee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
