# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_trackee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
