# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_trackee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackee',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
