# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171221_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('chatId', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trackee',
            name='last',
        ),
        migrations.AddField(
            model_name='trackee',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tracker'),
        ),
    ]
